#!/usr/bin/env bash
# install Nginx server and redirects /rediredt_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/bahailu-abera permanent;/" /etc/nginx/sites-available/default 
service nginx start
