#!/usr/bin/env bash
# install Nginx server and redirects /rediredt_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\t rewrite ^\/redirect_me https:\/\/github.com\/bahailu-abera permanent;\n\t}"
sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-available/default

error_page="Ceci n'est pas une page"
echo "$error_page" | sed -i -n '1w \/usr\/share\/nginx\/html\/custom_404.html'
conf_content="server_name _;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/${conf_content}/" /etc/nginx/sites-available/default

service nginx start
