#!/usr/bin/env bash
# customize Not Found page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\t rewrite ^\/redirect_me https:\/\/github.com\/bahailu-abera permanent;\n\t}"
sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-available/default
error_page="Ceci n'est pas une page"
echo "$error_page" > /usr/share/nginx/html/custom_404.html
conf_code="error_page 404\/custom_404.html;\nlocation = \/custom_404.html {\troot \/usr\/share\/nginx\/html;\n\tinternal;\n}"
sed -i "s/server_name _;/${conf_code}/" /etc/nginx/sites-enabled/default
service nginx restart
