#!/usr/bin/env bash
# a script to install and configure haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install haproxy=2.6.\*

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 3741-web-01 44.211.36.124 check\n\tserver 3741-web-02 3.236.150.149:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
