#!/usr/bin/env bash
#Fixes the nginx listening port and reloads the nginx master process
st="\tlisten 8080 default_server\;"
newst="\tlisten 80 default_server\;"
st2="\tlisten \[::\]:8080 default_server ipv4only=on"
newst2="\tlisten \[::\]:80 default_server ipv4only=on"
sudo sed -i "0,/$st/{s/$st/$newst/}" /etc/nginx/sites-enabled/default
sudo sed -i "0,/$st2/{s/$st2/$newst2/}" /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
