#!/usr/bin/env bash
# script to run nginx on port 80
pkill -9 apache2
pkill -9 nginx
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen [::]:8080/listen [::]:80/" /etc/nginx/sites-enabled/default
service nginx start
