#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100.

for num in {1..100}
do
	mod3=$((num % 3))
	mod5=$((num % 5))
	if [[ $mod3 -eq 0 && $mod5 -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [ $mod5 -eq 0 ]
	then
		echo "Buzz"
	elif [ $mod3 -eq 0 ]
	then
		echo "Fizz"
	else
		echo $num
	fi
done
