#!/usr/bin/env bash
# A bash script that gives information about the school file.
filename="school"

if [ ! -e "$filename" ]
then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ -s "$filename" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$filename" ]
	then
		echo "school is a regular file"
	fi
fi
